# Generated by Django 4.1.3 on 2022-11-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmapp', '0002_alter_actor_t_yil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kino',
            name='yil',
            field=models.DateField(),
        ),
    ]
